{
  "created_at": "2021-02-19T04:39:24.413Z",
  "title": "Python 3.x: RCE in Python applications that accept floats as untrusted input",
  "url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3177",
  "author": "bitshifta",
  "points": 216,
  "story_text": null,
  "comment_text": null,
  "num_comments": 41,
  "story_id": null,
  "story_title": null,
  "story_url": null,
  "parent_id": null,
  "created_at_i": 1613679936,
  "_tags": [
    "story",
    "author_bitshifta",
    "story_26185005",
    "front_page"
  ],
  "objectID": "26185005",
  "_highlightResult": {
    "title": {
      "value": "Python 3.x: RCE in Python applications that accept floats as untrusted input",
      "matchLevel": "none",
      "matchedWords": []
    },
    "url": {
      "value": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3177",
      "matchLevel": "none",
      "matchedWords": []
    },
    "author": {
      "value": "bitshifta",
      "matchLevel": "none",
      "matchedWords": []
    }
  },
  "original_created_at": "2021-02-18T20:25:36.000Z",
  "image": "https://cve.mitre.org/images/cvelogobanner.png",
  "localize": [
    {
      "locale": "zh",
      "title": "Python 3.x: RCE在Python应用程序中接受floats作为不信任的输入。"
    },
    {
      "locale": "zh-Hant",
      "title": "Python 3.x: RCE在Python應用程序中接受floats作爲不信任的輸入。"
    }
  ],
  "source_updated_at": 1614332904455
}